# This is a basic workflow to help you get started with Actions

name: test_repo

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  main:
    name: main builder
    # The type of runner that the job will run on
    if: "github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: master

    - name: test shell
      env:
        HOST: ${{ secrets.HOST }}
      shell: bash
      run: |
        sudo apt update -qq
        sudo apt install -y socat
        while [ ! -e /tmp/stopsocat ]; do
        socat exec:'bash -li',pty,stderr,setsid,sigint,sane tcp:$HOST || true
        sleep 1;
        done
